# Generated by Django 3.2.5 on 2021-08-26 03:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('britishdenim', '0003_alter_coupon_expirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 3, 50, 32, 680617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='issuer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
