# Generated by Django 3.2.5 on 2021-08-26 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('britishdenim', '0006_auto_20210826_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 26, 4, 53, 47, 572805, tzinfo=utc)),
        ),
    ]
